### ISSUE TITLE
Show bundle in browser

### ISSUE THREAD

**Issue by aik** [getpatchwork/patchwork#120]
Right now clicking on "download" downloads the file. Firefox 55.

I'd really prefer just seeing it in browser as is - this way I can run "git am" and simply cut-n-paste from browser to the terminal and avoid downloading/saving/opening/deleting temporary files. Same request about "diff" and "mbox" buttons in the individual patches.

The workaround I used before (2 firefox addons) to show files in a browsers won't work anymore in a month or two as Firefox is migrating to the new addons api. Or is there any other workaround?

**Comment by ajdlinux** [comment]
@mpe @daxtens @ruscur @stephenfin any thoughts on the best default behaviour here?

**Comment by stephenfin** [comment]
I'm conflicted. On one hand, I understand the usability concerns here and would like to fix this. On the other, the whole reason this download is because of the `Content-Type` header we're returning and `text/mbox` (I think?) seems correct.

What about doing something like Gerrit, namely a drop-down that would let users select how they want to access the file.

![image](https://user-images.githubusercontent.com/1690835/34676053-63698434-f483-11e7-9ae2-ad33ef8cc8fa.png)

We'd have "View in browser" and "Download" as options. We may also wish to add commands for `git-pw` too, but that's a nice-to-have and maybe unnecessary. Thoughts?

**Comment by ajdlinux** [comment]
It's not just because of `Content-Type`, we manually add a `Content-Disposition: attachment` header as well.

**Comment by stephenfin** [comment]
> It's not just because of Content-Type, we manually add a Content-Disposition: attachment header as well.

Oh, I hadn't spotted that. The "some users _want_ to download it" point probably still stands though. Sounds very much like behaviour that should be customizable in some way

**Comment by ajdlinux** [comment]
Yeah, personally I'd prefer and expect download by default.

The difficulty with a dropdown is that we have already have three buttons, so adding a dropdown to each of those would really clutter up the interface. But maybe there's a good way to do that...

We could also add a user profile option to set download vs view globally on a per user basis?

**Comment by mpe** [comment]
I think it should download by default.

Making it a user preference seems like the best option.

**Comment by mpe** [comment]
In fact the whole workflow of copy and pasting just seems a bit silly TBH.

With a tiny script saved as `apply-from-patchwork`:
```
#!/bin/bash

wget -O http://patchwork.ozlabs.org/patch/$1/mbox/ | git am
```

You can then apply the patch with id 12345 with:
```
$ apply-from-patchwork 12345
```

This is what motivated the `show_ids` feature, so that copying and pasting the patch id is a single click. 

So I'd be inclined to close WONT_FIX.

**Comment by ajdlinux** [comment]
Or use `pwclient` or `git-pw` as the officially supported ways of doing that...

If there is enough demand though, adding an extra user profile field wouldn't be much effort.

**Comment by aik** [comment]
"show_ids" does not work in firefox 57. I'll file it separately now.

About download vs. show - I know workarounds, all of them involve one more tool/script in addition to a browser and git + need to configure external access everywhere I want "git ams" to work. It is doable but just annoying.

Right now the browser opens "pluma" (some default fedora/mate editor) and I cut-n-paste from it, works for me. So if it is just me, then WONT_FIX is alright.

**Comment by ajdlinux** [comment]
working on a patch

**Comment by aik** [comment]
Firefox addon received an update for firefox v60: https://addons.mozilla.org/en-US/firefox/addon/open-in-browser
So there is no need in hacking pw for this anymore.

**Comment by stephenfin** [comment]
Excellent. I'll close this out unless anyone decides they *really* need this.
