### ISSUE TITLE
Click on the "id" button from "show_ids" does nothing in Firefox 57

### ISSUE THREAD

**Issue by aik** [getpatchwork/patchwork#150]
$(subj). It is supposed to copy to clipboard or something. Cannot it be just text so doubleclick on it could copy it to the clipboard?

**Comment by ajdlinux** [comment]
Works fine for me on Firefox 57.

**Comment by ajdlinux** [comment]
Are there any errors appearing in the browser JavaScript console?

**Comment by aik** [comment]
none, none of id buttons produces anything in "browser console" or any other console. where should I look at?

**Comment by ajdlinux** [comment]
No idea. It works fine here on Firefox 57.0.4, so I know it's not *completely* broken in Firefox...

**Comment by stephenfin** [comment]
@aik Any chance of getting a screencast so we can see what you're trying to do. Also working here with both Firefox and Chromium. I assume you don't have JavaScript disabled?

**Comment by aik** [comment]
no cast, sorry. and I simply click on the id button. I used a default FF profile with no addons or other adjustments so JS should just work. Same happens on @mpe 's FF so it is probably not "mate" desktop fault.
 Anyway, why not just show text id so double click could copy it to the clipboard?

**Comment by daxtens** [comment]
So I have a theory about what might be the issue here.

@aik and @mpe, are you talking about the ^C/^V clipboard, or the selection/middle-mouse/shift-insert clipboard?

The javascript will put the ID in the ^C/^V clipboard, not the old-school shift-insert clipboard. If you're wanting it to put it in the shift-insert clipboard, that would be pretty easy for us to do.

Regards,
Daniel

**Comment by aik** [comment]
left click on the id button and then middle click in the mate-terminal - which clipboard is it?

**Comment by daxtens** [comment]
Ah, that's not the clipboard we are copying to! If you press
Control-Shift-V it should paste into the terminal.

I will write a patch that copies into the clipboard you use.

**Comment by stephenfin** [comment]
I'd no idea that was even a thing 😮 Interesting...

**Comment by mpe** [comment]
Yes you're right. To be pedantic that's the "CLIPBOARD" (Ctrl-v) vs the "PRIMARY SELECTION" (shift insert).

I guess Chromium copies to both by default. Up to you whether you think it's patchwork's job to care about that level of detail. But I guess if it's easy to copy to both then that would be preferable.

**Comment by stephenfin** [comment]
codemirror/CodeMirror#931 looks related

**Comment by ajdlinux** [comment]
@daxtens I take it you didn't get anywhere with this?

Having done a bit of Googling about the subject - I'm going to close this as it looks to be a Firefox limitation, not explicitly documented anywhere.

**Comment by aik** [comment]
Firefox 71b06, the issue persist. Please make it text. Thanks.

**Comment by mpe** [comment]
NAK :hammer:

**Comment by ajdlinux** [comment]
Yeah mpe mode is going to stay I think, if anything this should be reported as a bug in Firefox

**Comment by aik** [comment]
and what is the bug to report exactly? I complained about the design when text is not text == not selectable. My proposal replaces a single click with a double click (which is what the rest of linux UI does), yours is what, switch to chromium? ah, never mind, there are weirded things with pw anyway.

**Comment by ajdlinux** [comment]
Firefox's behaviour when using Document.execCommand() to copy text to the clipboard on Linux is to copy into CLIPBOARD but not PRIMARY, while Chrome does both. That is certainly unexpected to me and would be worthy of a bug report to Mozilla.

The single-click to copy behaviour is there due to specific user request. Having single-click copy buttons is fairly standard in web-based developer tools these days - though admittedly ours is not quite as discoverable as I'd like it to be.

**Comment by aik** [comment]
It is not "fairly standard" and where it exists - it is a text box with a "copy" button next to it.

**Comment by aik** [comment]
Still find it very annoying that the id is not a selectable text anywhere on a page or url but just a button. I constantly paste entire patches to the console and ruin the shell history.
