### ISSUE TITLE
Clicking on "page two" drops archive filter and returns 500 server error

### ISSUE THREAD

**Issue by eli-schwartz** [getpatchwork/patchwork#184]
See for example https://patchwork.archlinux.org/project/pacman/list/?state=%2A&archive=both

The link provided is https://patchwork.archlinux.org/project/pacman/list/?state=*&page=2

If I manually add &archive=both I get https://patchwork.archlinux.org/project/pacman/list/?state=*&archive=both&page=2 which works as expected.

version v2.0.0.postrc4

**Comment by stephenfin** [comment]
I'm able to reproduce the dropping of the `archive` filter but I don't see any errors. Do you know if it's possible to get logs from the admin of this instance so I can investigate further?

**Comment by grazzolini** [comment]
Hi @stephenfin, I'm going to update this patchwork installation to the latest version. If the bug still persists, I'll get a log. Please, leave this bug open for at least one more week.

**Comment by stephenfin** [comment]
@eli-schwartz @grazzolini I have this resolved on master and stable/2.0 meaning this will be included in v2.1.0 and v2.0.3. Could I ask you to test this on v2.0.2 though so I can get the reason for the HTTP 500 error? I imagine that's something else going on.

**Comment by grazzolini** [comment]
Hi @stephenfin, surely, I'll test this. I'm planning on updating our patchwork version this weekend. If you can, please check how our installation was done at: https://git.archlinux.org/infrastructure.git/tree/roles/patchwork. Everything is set using ansible, and since our previous patchwork version was very, very old (it was still django 1.2), I was not able to upgrade it, so I went with a clean install, from scratch.
