### ISSUE TITLE
Incorrect submitter when using googlegroups

### ISSUE THREAD

**Issue by alexandrebelloni** [getpatchwork/patchwork#64]
Sometimes, google groups rewrites the From: header to itself. I guess this is when people are sending mails to the mailing list without subscribing to it.

The issue is that then, patchwork thinks the submitter is the mailing list and ends up using the name of the first person that sent a mail that way.
Example: http://patchwork.ozlabs.org/patch/700832/

**Comment by ajdlinux** [comment]
This is probably due to SPF/DMARC forcing the mailing list to rewrite the From: header so that the resulting mail doesn't fail at spam filtering on the other side. This is pretty common among mailing lists that append footers to the end of the email, thus changing the signature.

Over on linuxppc-dev@lists.ozlabs.org, my understanding is that we resolved this by removing the footer in the Mailman settings so that it could use the unmodified signature. (@daxtens, @ruscur do you remember?)

It looks like in this case, there's an X-Original-Sender header which could be matched. However that doesn't solve the problem in the general case - going back through my mail archives, it looks like Mailman doesn't add that header when it rewrites, and the only thing you have to go off is that it keeps the original Reply-To.

I suppose Mailman plus Google Groups probably covers the vast majority of patchwork-using lists, so we could perhaps special-case both of them...

**Comment by daxtens** [comment]
My recollection is that sfr fought a long battle with Mailman to stop it
changing anything in the message so that the signature didn't fail.

We may well have to special case anything that does want to mangle messages.

Regards,
Daniel

**Comment by ajdlinux** [comment]
This has been raised again regarding one of the ozlabs.org lists where mailman does from address munging. I think we just special-case mailman + google groups and that should cover most cases

**Comment by ajdlinux** [comment]
Working on this

**Comment by ajdlinux** [comment]
I've got patches for this, just have to write some tests

**Comment by daxtens** [comment]
Yay, let's get this in 2.2.
