### ISSUE TITLE
Patchwork picks incorrect email address

### ISSUE THREAD

**Issue by xypron** [getpatchwork/patchwork#98]
I have submitted https://patchwork.ozlabs.org/patch/758781/mbox/ with

    git send-email --from="Heinrich Schuchardt <xypron.glpk@gmx.de>"

The copy I received from my email provider has:

    Return-Path: <xypron.glpk@gmx.de>
    From: Heinrich Schuchardt <xypron.glpk@gmx.de>

The mbox file stored by patchwork has

    From patchwork Thu May  4 20:26:42 2017
    Content-Type: text/plain; charset="utf-8"
    MIME-Version: 1.0 
    Content-Transfer-Encoding: 7bit
    Subject: [U-Boot,v2,1/1] tools: sunxi: avoid read after end of string
    From: xypron.glpk@gmx.de

Why does patchwork loose my name in the From: field?

Best regards

Heinrich Schuchardt

**Comment by xypron** [comment]
Other online archives correctly picked my name form the message header: https://www.mail-archive.com/u-boot@lists.denx.de/msg247611.html

**Comment by stephenfin** [comment]
This was fixed in `48c0e00a` on `stable/1.1`, which later became `v1.1.3` (it's also fixed in `d365402f` on `master`). Unfortunately, patchwork.ozlabs.org hasn't been updated to this version and I'm not the admin for that instance. You will need to email the instance admin directly and request this update.
